name: "ArvanCloud PaaS Action"
author: "Arash Hatami"
description: "Deploy new changes to ArvanCloud PaaS"
branding:
  icon: "cloud"
  color: "blue"
inputs:
  version:
    description: "The version of CLI tool to use"
    required: false
    default: "1.3.6"
  region:
    description: "Your ArvanCloud Region"
    required: false
    default: "1"
  auth:
    description: "Your ArvanCloud API auth token"
    required: true
  app:
    description: "The ArvanCloud app to deploy to"
    required: true
  container:
    description: "The ArvanCloud container to deploy to"
    required: true
  image:
    description: "Your new image to deploy"
    required: true
  namespace:
    description: "The target namespace ( project )"
    required: false
    default: "default"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.version }}
    - ${{ inputs.region }}
    - ${{ inputs.auth }}
    - ${{ inputs.app }}
    - ${{ inputs.container }}
    - ${{ inputs.image }}
    - ${{ inputs.namespace }}
