name: "ArvanCloud PaaS Action"
author: "Arash Hatami"
description: "Deploy new changes to ArvanCloud PaaS"
branding:
  icon: "cloud"
  color: "blue"
inputs:
  auth:
    description: "Your ArvanCloud API auth token"
    required: true
  app:
    description: "The ArvanCloud app to deploy to"
    required: true
  container:
    description: "The ArvanCloud container to deploy to"
    required: true
  image:
    description: "Your new image to deploy"
    required: true
  version:
    description: "The version of the CLI"
    required: false
    default: "1.0.3"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.version }}
    - ${{ inputs.auth }}
    - ${{ inputs.app }}
    - ${{ inputs.container }}
    - ${{ inputs.image }}
